### ISSUE TITLE
The archives created from github should include submodules

### ISSUE THREAD

**Issue by davidanthoff** [zenodo/zenodo#1036]
It would be great if the archive that gets automatically created when I create a release on github would include any git submodules that my git repo might contain. I believe that e.g. this package  https://github.com/Kentzo/git-archive-all makes that pretty simple.

**Comment by krzysztof** [comment]
One thing to consider is whether we would have the rights to include all submodules code in the archive along with the user's code.

**Comment by cmbant** [comment]
Regarding rights: this would not be an issue for repositories where all submodules are also on zenodo, so this could at least be enabled for restricted cases. Including the submodules is of course essential for the code to actually be reproducible.

**Comment by CSchoel** [comment]
As workaround one could use a CI script which generates releases that include the content of the relevant submodules as asset. However, due to #1235 , this currently also does not work.

For example, this is the setup I use for Travis CI:

```yaml
before_deploy:
  - zip -r inamo-${TRAVIS_TAG}.zip . -x out\* plots\* .git\* regRefData/.git\*

deploy:
  provider: releases
  edge: true
  api_key:
    secure: "***"
  file: inamo-${TRAVIS_TAG}.zip
  release_notes_file: README.md
  tag_name: ${TRAVIS_TAG}
  name: InaMo ${TRAVIS_TAG}
  on:
    tags: true
  draft: true
```
