### ISSUE TITLE
github: inclusion of release assets in published record

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1235]
It's common for GitHub releases to include release "assets". Since the zipball of the source code is already downloaded, it might be also worth looking at downloading and including the assets in the produced record.  

File sizes are limited to 2GB per file, though there's no limit in the number of files, so soe checking is required before attempting to download the assets.

**Comment by sdruskat** [comment]
If by *assets* you mean additional files added to a release on GitHub before it is published, that would indeed be a great thing to have!

**Comment by luizirber** [comment]
Pinging in this issue with an use case: I have a [repo](https://github.com/luizirber/phd/) for my thesis, and on [a new release](https://github.com/luizirber/phd/releases/tag/2020.09.18) a PDF with the rendered content is uploaded to the release [using GH actions](https://github.com/luizirber/phd/runs/1136681451?check_suite_focus=true#step:9:8).

I would like to see it show up [in the Zenodo record](https://zenodo.org/record/4037513), in the "Files" section.

**Comment by CSchoel** [comment]
Adding another use case: I have a project for a [mathematical model of the AV node](https://github.com/CSchoel/inamo) which includes [reference simulation results]((https://github.com/CSchoel/inamo-ref)) as a git submodule. Since GitHub does not include the contents of submodules in the automatically generated zip file of the repository, I have set up a Travis CI script that builds a zip file, which also includes these additional files and is automatically added to the release when a new tag is published.

It would be really nice if this zip file would show up on Zenodo, since automating Zenodo publications was the reason why I added this to the CI script in the first place.

**Comment by vivi90** [comment]
> Pinging in this issue with an use case: I have a [repo](https://github.com/luizirber/phd/) for my thesis, and on [a new release](https://github.com/luizirber/phd/releases/tag/2020.09.18) a PDF with the rendered content is uploaded to the release [using GH actions](https://github.com/luizirber/phd/runs/1136681451?check_suite_focus=true#step:9:8).
> 
> I would like to see it show up [in the Zenodo record](https://zenodo.org/record/4037513), in the "Files" section.

Same for me.

**Comment by lorenzleutgeb** [comment]
This also helps with computer science conferences that evaluate artifacts. I have code in repo that generates this artifact, and could attach it to a release as well.

**Comment by jemissik** [comment]
I have a common of use case for which this feature would be very useful: 
Many projects include the source files for documentation in the repository, but not a rendered version of the documentation. For example, many of my projects use Sphinx for the documentation pages, which are hosted on Read The Docs and are built there automatically. The documentation source files are kept in the repository, but not a rendered version of the pages. But, I can also include a rendered PDF version of the documentation as a release asset. It would be great if this could be included in the Zenodo archive along with the source code.

**Comment by johentsch** [comment]
This feature would be essential for archiving our research data, too: Every release results in the creation of a [Frictionless datapackage](https://specs.frictionlessdata.io/data-package/) which concatenates all data contained in the repository in a specific way and this datapackage is the principal way that our users interact with the data. It would be very relevant to include these release assets with the files archived on Zenodo and, on top of that, the [Frictionless framework](https://framework.frictionlessdata.io/) allows for loading these datapackages directly from Zenodo.

Also, this feature could somewhat mitigate #1036, which is another problem we have: Archiving GitHub repositories does not include submodules other than as empty folders. Since our datapackages do, including release assets would solve this problem for us.

**Comment by RemDelaporteMathurin** [comment]
Another use case: as part of our research project, we would like to upload raw experimental data to a repo, then at each release, create a file with the processed experimental data from the scripts in the repo, and add this as a release asset (and to Zenodo)

**Comment by RemDelaporteMathurin** [comment]
I very naively asked ChatGPT how we could achieve this with GitHub action and this is what it came up with.... i have very little faith that it works but maybe this will give some ideas?


```yml
name: Upload GitHub Release Assets to Zenodo

on:
  release:
    types: [published]

jobs:
  upload-assets-to-zenodo:
    runs-on: ubuntu-latest

    steps:
    - name: Get release assets
      id: get-assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching release assets..."
        RELEASE_ASSETS=$(curl -s \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets" \
          | jq -r '.[] | .browser_download_url')
        echo "RELEASE_ASSETS=$RELEASE_ASSETS" >> $GITHUB_ENV

    - name: Download release assets
      run: |
        mkdir assets
        for url in $RELEASE_ASSETS; do
          echo "Downloading $url..."
          curl -L -o "assets/$(basename $url)" "$url"
        done

    - name: Upload to Zenodo
      env:
        ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
      run: |
        # Replace with your Zenodo deposition ID
        DEPOSITION_ID="your_deposition_id"

        # Loop through downloaded assets and upload them
        for file in assets/*; do
          echo "Uploading $file to Zenodo..."
          curl -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
               -F "file=@$file" \
               "https://zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files"
        done

```
